on: push
name: Angular Build
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v1
      
      - name: npm install and ng build
        run: |
          npm install
          ng build
            
