on: push
name: Angular Build
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]


   steps:
      - uses: actions/checkout@v1

      - name: build docker image and push to docker hub 
        run: docker build -t dexterlabhunter/angular-actions ./

      - name: login to docker hub 
        uses: docker/login-action@v2 
        with: 
         username: dexterlabhunter
         password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Docker push
        run: docker push dexterlabhunter/angular-actions
